### PR TITLE
Add note about JavaCAN use in Apache PLC4X

### PR DESCRIPTION
**Pull request by splatch**
While this change is small it is brought here to spread a good message about JavaCAN! :)

### CODE REVIEW

**Comment by pschichtel** [comment]
@splatch I just found this by pure coincidence, was this meant for the main repo?

**Comment by splatch** [comment]
@pschichtel You bet!

Throwing some more context - I made this repo through github ui and apparently got lost with it.

**Comment by pschichtel** [comment]
@splatch do you want to reopen the PR against my repo or should I just cherry-pick it from your repo here?

**Comment by splatch** [comment]
Moving it to target repo!

**Pull request closed without merging**
